/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_howell_utils_TalkJniUtil */

#ifndef _Included_com_howell_utils_TalkJniUtil
#define _Included_com_howell_utils_TalkJniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_howell_utils_TalkJniUtil
 * Method:    talkInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_utils_TalkJniUtil_talkInit
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_utils_TalkJniUtil
 * Method:    talkDeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_utils_TalkJniUtil_talkDeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_utils_TalkJniUtil
 * Method:    setCallbackObj
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_howell_utils_TalkJniUtil_setCallbackObj
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_howell_utils_TalkJniUtil
 * Method:    setCallbackMethodName
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_howell_utils_TalkJniUtil_setCallbackMethodName
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_howell_utils_TalkJniUtil
 * Method:    register2svr
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_howell_utils_TalkJniUtil_register2svr
  (JNIEnv *, jclass, jstring, jstring, jstring, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
